name: ci
on: [push, pull_request]
jobs:
  python-unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: python3 -m unittest